### ISSUE TITLE
mvp roadmap

### ISSUE THREAD

**Issue by 2blo** [2blo/blume#1]
- [x] convert html files to ebook.
- [ ] change age of characters
- [ ] change gender of characters
- [ ] take kindle ebook as input
